// Code generated by goctl. DO NOT EDIT!
// Source: file.proto

package server

import (
	"context"

	"grpc-storage/service/file-storage/rpc/internal/logic"
	"grpc-storage/service/file-storage/rpc/internal/svc"
	"grpc-storage/service/file-storage/rpc/types/filegrpc"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	filegrpc.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

// image grpc call
func (s *FileServer) CreateImage(ctx context.Context, in *filegrpc.ImageCreateRequest) (*filegrpc.ImageResponse, error) {
	l := logic.NewCreateImageLogic(ctx, s.svcCtx)
	return l.CreateImage(in)
}

func (s *FileServer) GetImage(ctx context.Context, in *filegrpc.ImageGetRequest) (*filegrpc.ImageGetResponse, error) {
	l := logic.NewGetImageLogic(ctx, s.svcCtx)
	return l.GetImage(in)
}

func (s *FileServer) DeleteImage(ctx context.Context, in *filegrpc.ImageDeleteRequest) (*filegrpc.ImageDeleteResponse, error) {
	l := logic.NewDeleteImageLogic(ctx, s.svcCtx)
	return l.DeleteImage(in)
}

// video grpc call
func (s *FileServer) Createvideo(ctx context.Context, in *filegrpc.VidoeCreateRequest) (*filegrpc.VideoCreateResponse, error) {
	l := logic.NewCreatevideoLogic(ctx, s.svcCtx)
	return l.Createvideo(in)
}

func (s *FileServer) Getvideo(ctx context.Context, in *filegrpc.VideoGetRequest) (*filegrpc.VideoGetResponse, error) {
	l := logic.NewGetvideoLogic(ctx, s.svcCtx)
	return l.Getvideo(in)
}

func (s *FileServer) Deletevideo(ctx context.Context, in *filegrpc.VideoDeleteRequest) (*filegrpc.VideoDeleteResponse, error) {
	l := logic.NewDeletevideoLogic(ctx, s.svcCtx)
	return l.Deletevideo(in)
}
